/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hu.web220.dependency.analyzer.core;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;

import java.io.File;

import static org.junit.jupiter.api.Assertions.assertTrue;

class LibraryConnectionsSearchTaskTest {
    File projectDir = new File("../");
    BuildResult result;

    @Test
    void canRunTaskAndOutputIsRight() {
        runGradleTask();
        asserts();
    }

    private void runGradleTask() {
        result = GradleRunner.create()
                .forwardOutput()
                .withPluginClasspath()
                .withArguments(
                        "searchLibraryConnections",
                        "-Plib=org.apache.commons:commons-math3:3.6.1",
                        "-Plist",
                        "-Pstats",
                        "-Pcircular")
                .withProjectDir(projectDir)
                .build();
    }

    private void asserts() {
        assertInput();
        assertCircularDependencyWarning();
    }

    private void assertInput() {
        assertTrue(result.getOutput().contains(
                "Given input (trimmed to 200 character length) is: org.apache.commons:commons-math3:3.6.1"));
    }

    private void assertCircularDependencyWarning() {
        assertTrue(result.getOutput().contains(
                "!!! Warning !!! Circular dependencies detected"));
    }
}
