/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hu.web220.dependency.analyzer.core;

import hu.web220.dependency.analyzer.core.tasks.PrintTask;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.artifacts.ConfigurationContainer;
import org.gradle.api.artifacts.Dependency;
import org.gradle.api.artifacts.DependencySet;

/**
 * A simple 'hello world' plugin.
 */
public class DependencyAnalyzerPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("printAllDependencies", PrintTask.class);
    }
}
