/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hu.web220.dependency.analyzer.core;

import hu.web220.dependency.analyzer.core.tasks.LibraryConnectionsSearchTask;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
public class DependencyAnalyzerPlugin implements Plugin<Project> {

    public static final String TASK_GROUP = "dependency-analyzer";

    public void apply(Project project) {
        project.getTasks().register("searchLibraryConnections", LibraryConnectionsSearchTask.class);
    }
}
